"""initial schema

Revision ID: 7455e4b31551
Revises: 
Create Date: 2026-08-21 00:30:19.252581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7455e4b31551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrient_reference',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('category', sa.Enum('macro', 'vitamin', 'mineral', 'other', name='nutrientcategory', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('devices',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.Enum('ios', 'android', 'web', name='deviceplatform', native_enum=False), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_devices_user_device', 'devices', ['user_id', 'device_id'], unique=True)
    op.create_table('foods',
    sa.Column('source', sa.Enum('local', 'off', 'usda', name='foodsource', native_enum=False), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('serving_size_g', sa.Float(), nullable=True),
    sa.Column('serving_unit_label', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_foods_barcode', 'foods', ['barcode'], unique=False)
    op.create_index('ix_foods_name', 'foods', ['name'], unique=False)
    op.create_index(op.f('ix_foods_updated_at'), 'foods', ['updated_at'], unique=False)
    op.create_index('ux_foods_source_source_id', 'foods', ['source', 'source_id'], unique=True, sqlite_where=sa.text('source_id IS NOT NULL'))
    op.create_table('rda_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nutrient_code', sa.String(length=16), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'any', name='rdasex', native_enum=False), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('rda_amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_code'], ['nutrient_reference.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_updated_at'), 'recipes', ['updated_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sex', native_enum=False), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activitylevel', native_enum=False), nullable=True),
    sa.Column('goal', sa.Enum('lose', 'maintain', 'gain', name='goal', native_enum=False), nullable=True),
    sa.Column('weekly_goal_rate_kg', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_updated_at'), 'user_profiles', ['updated_at'], unique=False)
    op.create_table('user_targets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('calculated', 'manual', name='targetsource', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_targets_updated_at'), 'user_targets', ['updated_at'], unique=False)
    op.create_index('ix_user_targets_user_effective', 'user_targets', ['user_id', 'effective_date'], unique=False)
    op.create_table('food_micronutrients',
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('nutrient_code', sa.String(length=16), nullable=False),
    sa.Column('amount_per_100g', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['nutrient_code'], ['nutrient_reference.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_micronutrients_food_nutrient', 'food_micronutrients', ['food_id', 'nutrient_code'], unique=False)
    op.create_index(op.f('ix_food_micronutrients_updated_at'), 'food_micronutrients', ['updated_at'], unique=False)
    op.create_table('food_nutrients',
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id')
    )
    op.create_index(op.f('ix_food_nutrients_updated_at'), 'food_nutrients', ['updated_at'], unique=False)
    op.create_table('log_entries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=True),
    sa.Column('recipe_id', sa.String(length=36), nullable=True),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('quantity_servings', sa.Float(), nullable=True),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtype', native_enum=False), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(food_id IS NOT NULL AND recipe_id IS NULL) OR (food_id IS NULL AND recipe_id IS NOT NULL)', name='ck_log_entries_exactly_one_of_food_recipe'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_updated_at'), 'log_entries', ['updated_at'], unique=False)
    op.create_index('ix_log_entries_user_date', 'log_entries', ['user_id', 'log_date'], unique=False)
    op.create_index('ix_log_entries_user_updated', 'log_entries', ['user_id', 'updated_at'], unique=False)
    op.create_table('recipe_items',
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_items')
    op.drop_index('ix_log_entries_user_updated', table_name='log_entries')
    op.drop_index('ix_log_entries_user_date', table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_updated_at'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_food_nutrients_updated_at'), table_name='food_nutrients')
    op.drop_table('food_nutrients')
    op.drop_index(op.f('ix_food_micronutrients_updated_at'), table_name='food_micronutrients')
    op.drop_index('ix_food_micronutrients_food_nutrient', table_name='food_micronutrients')
    op.drop_table('food_micronutrients')
    op.drop_index('ix_user_targets_user_effective', table_name='user_targets')
    op.drop_index(op.f('ix_user_targets_updated_at'), table_name='user_targets')
    op.drop_table('user_targets')
    op.drop_index(op.f('ix_user_profiles_updated_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_recipes_updated_at'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('rda_targets')
    op.drop_index('ux_foods_source_source_id', table_name='foods', sqlite_where=sa.text('source_id IS NOT NULL'))
    op.drop_index(op.f('ix_foods_updated_at'), table_name='foods')
    op.drop_index('ix_foods_name', table_name='foods')
    op.drop_index('ix_foods_barcode', table_name='foods')
    op.drop_table('foods')
    op.drop_index('ux_devices_user_device', table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('nutrient_reference')
    # ### end Alembic commands ###
